apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-name
  labels:
    type: local

spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data

---

apiVersion : v1
kind : PersistentVolumeClaim
metadata :
  name : pvc-name

spec :
  storageClassName : manual
  resources :
    requests :
     storage : 3Gi
  accessModes :
   - ReadWriteOnce
  volumeName : pv-name
